parameters:
    app.uploads.blocs_dir: '%kernel.project_dir%/public/uploads/blocs'
    app.uploads.blocs_path: 'uploads/blocs'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Service\UploadManager:
        arguments:
            $blocsUploadDir: '%app.uploads.blocs_dir%'
            $blocsUploadPath: '%app.uploads.blocs_path%'

    App\Controller\Admin\MediaCrudController:
        arguments:
            $blocsUploadDir: '%app.uploads.blocs_dir%'
            $blocsUploadPath: '%app.uploads.blocs_path%'

    App\Controller\Admin\ParametreCrudController:
        arguments:
            $blocsUploadPath: '%app.uploads.blocs_path%'